"""create episodes table

Revision ID: 666969ff4951
Revises: eed0dd60641a
Create Date: 2026-09-23 15:38:09.604092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666969ff4951'
down_revision: Union[str, None] = 'eed0dd60641a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'number', name='uq_episode_anime_number')
    )
    op.create_index(op.f('ix_episodes_anime_id'), 'episodes', ['anime_id'], unique=False)
    op.create_index(op.f('ix_episodes_id'), 'episodes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_anime_id'), table_name='episodes')
    op.drop_table('episodes')
    # ### end Alembic commands ###
