"""create library_entries table

Revision ID: 99475772f590
Revises: f3d80bc2d6b8
Create Date: 2026-09-21 17:32:01.733676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99475772f590'
down_revision: Union[str, None] = 'f3d80bc2d6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'WATCHING', 'COMPLETED', 'ON_HOLD', 'DROPPED', name='library_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_library_user_anime')
    )
    op.create_index(op.f('ix_library_entries_anime_id'), 'library_entries', ['anime_id'], unique=False)
    op.create_index(op.f('ix_library_entries_id'), 'library_entries', ['id'], unique=False)
    op.create_index(op.f('ix_library_entries_status'), 'library_entries', ['status'], unique=False)
    op.create_index(op.f('ix_library_entries_user_id'), 'library_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_entries_user_id'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_status'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_id'), table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_anime_id'), table_name='library_entries')
    op.drop_table('library_entries')
    # ### end Alembic commands ###
